Works for a while but crashes
With this error:

Traceback (most recent call last):
  File "org.jpype.pkg.JPypePackage.java", line -1, in org.jpype.pkg.JPypePackage.getObject
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Users\he_de\workspace\OpenRocketQD\evolve_rockets.py", line 854, in <module>
    f"{metrics['Archive Coverage']['y'][-1] * 100:.3f}% "
  File "E:\Users\he_de\workspace\OpenRocketQD\orhelper\_orhelper.py", line 87, in __exit__
    for window in jpype.java.awt.Window.getWindows():
java.lang.java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: E:\Program Files\Java\jdk1.8.0_291\jre\bin\awt.dll: The paging file is too small for this operation to complete